import json
import os
import boto3
import time
import math
from datetime import datetime, timedelta
from jinja2 import Template
import urllib.parse

s3_client = boto3.client('s3')
dynamodb = boto3.resource('dynamodb')
TABLE_NAME = os.environ['TABLE_NAME']
TEMPLATES_BUCKET = os.environ['TEMPLATES_BUCKET']
table = dynamodb.Table(TABLE_NAME)

def lambda_handler(event, context):
    # 1. Parse input
    body = json.loads(event.get('body', '{}'))
    volume_tb = body.get('data_volume_tb', 0)
    records_per_day_millions = body.get('records_per_day_millions', 0)
    query_complexity = body.get('avg_query_complexity', 'medium')
    latency_sec = body.get('max_query_latency_sec', 60)
    concurrent_users = body.get('concurrent_users', 5)
    user_id = event.get('requestContext', {}).get('authorizer', {}).get('principalId', 'anonymous')
    
    # 2. Decisão
    use_redshift = (volume_tb > 10 or 
                    (query_complexity == 'high' and latency_sec < 10 and concurrent_users > 10))
    
    # 3. Gerar template CFN
    template_url = generate_cloudformation_template(use_redshift, volume_tb, user_id)
    
    # 4. Estimativa de custo (mesmo código anterior)
    cost_breakdown = compute_cost_breakdown(volume_tb, records_per_day_millions, use_redshift)
    total_cost = sum(cost_breakdown.values())
    
    # 5. Diagrama Mermaid
    diagram = get_mermaid_diagram(use_redshift)
    
    # 6. Salvar no DynamoDB (incluindo URL do template)
    timestamp = datetime.utcnow().isoformat()
    ttl = int((datetime.utcnow() + timedelta(days=90)).timestamp())
    item = {
        'user_id': user_id,
        'timestamp': timestamp,
        'ttl': ttl,
        'input_params': body,
        'output_architecture': 'full_lakehouse_with_redshift' if use_redshift else 'light_lakehouse_athena',
        'cost_estimate': round(total_cost, 2),
        'cost_breakdown': cost_breakdown,
        'template_url': template_url
    }
    table.put_item(Item=item)
    
    # 7. Resposta final
    response = {
        "architecture_type": item['output_architecture'],
        "services": ['S3','Glue','LakeFormation','Athena'] + (['Redshift','QuickSight'] if use_redshift else []),
        "estimated_monthly_cost_usd": round(total_cost, 2),
        "cost_breakdown_per_service": cost_breakdown,
        "diagram_mermaid": diagram,
        "provisioning_steps": get_provisioning_steps(use_redshift),
        "cloudformation_template_url": template_url,
        "message": "Template CloudFormation gerado e disponível por 1 hora."
    }
    
    return {
        'statusCode': 200,
        'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'},
        'body': json.dumps(response)
    }

def generate_cloudformation_template(use_redshift, volume_tb, user_id):
    # Escolher template base
    if use_redshift:
        base_key = "base/redshift_lakehouse.yaml.j2"
    else:
        base_key = "base/athena_lakehouse.yaml.j2"
    
    # Baixar template base do S3
    try:
        obj = s3_client.get_object(Bucket=TEMPLATES_BUCKET, Key=base_key)
        template_content = obj['Body'].read().decode('utf-8')
    except Exception as e:
        # Fallback: usar um template embutido simples (para desenvolvimento)
        template_content = get_fallback_template(use_redshift)
    
    # Preparar variáveis para Jinja2
    variables = {
        "project_name": f"lakehouse-{user_id[:8]}-{int(time.time())}",
        "data_volume_tb": volume_tb,
        "redshift_node_type": "ra3.xlplus",
        "redshift_node_count": 2 if volume_tb < 50 else 4,
        "environment": "prod",
        "current_date": datetime.utcnow().strftime("%Y-%m-%d"),
    }
    
    # Renderizar template
    jinja_template = Template(template_content)
    rendered_yaml = jinja_template.render(**variables)
    
    # Fazer upload para S3 (prefixo generated/)
    key = f"generated/{variables['project_name']}.yaml"
    s3_client.put_object(Bucket=TEMPLATES_BUCKET, Key=key, Body=rendered_yaml.encode('utf-8'), ContentType='text/yaml')
    
    # Gerar URL pré-assinada (válida por 3600 segundos)
    url = s3_client.generate_presigned_url('get_object', Params={'Bucket': TEMPLATES_BUCKET, 'Key': key}, ExpiresIn=3600)
    return url

def get_fallback_template(use_redshift):
    # Template simples embutido caso o bucket não esteja pronto
    if use_redshift:
        return """AWSTemplateFormatVersion: 2010-09-09
Description: Lake House with Redshift - Generated by Lake House Designer
Parameters:
  ProjectName:
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-data"
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterIdentifier: !Sub "${ProjectName}-redshift"
      NodeType: {{ redshift_node_type }}
      NumberOfNodes: {{ redshift_node_count }}
"""
    else:
        return """AWSTemplateFormatVersion: 2010-09-09
Description: Lake House with Athena - Generated by Lake House Designer
Parameters:
  ProjectName:
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-data"
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: !Sub "${ProjectName}_db"
"""

def compute_cost_breakdown(volume_tb, records_per_day_millions, use_redshift):
    # Mesma função da fase 2
    cost = {}
    cost['S3'] = round(volume_tb * 1024 * 0.023 + (records_per_day_millions * 1e6 * 30) * 0.0000004, 2)
    cost['Glue'] = round(2 * 30 * 0.44, 2)
    cost['Athena'] = round(200 * 30 * 0.005, 2)
    if use_redshift:
        cost['Redshift'] = round(2 * 2.208 * 24 * 30, 2)
        cost['QuickSight'] = 30.0
    else:
        cost['Redshift'] = 0.0
        cost['QuickSight'] = 0.0
    cost['Lake Formation'] = 0.0
    return cost

def get_mermaid_diagram(use_redshift):
    if use_redshift:
        return """graph TD
        A[S3 Raw] --> B[Glue ETL]
        B --> C[S3 Curated]
        C --> D[Redshift]
        D --> E[QuickSight]
        C --> F[Athena]"""
    else:
        return """graph TD
        A[S3 Raw] --> B[Glue ETL]
        B --> C[S3 Curated]
        C --> F[Athena]"""

def get_provisioning_steps(use_redshift):
    steps = [
        "1. Fazer upload do template CloudFormation no console AWS ou via CLI",
        "2. Executar `aws cloudformation create-stack --stack-name lakehouse-designer --template-body file://template.yaml`",
        "3. Após criação, configurar Lake Formation com permissões"
    ]
    if use_redshift:
        steps.insert(1, "1b. Verificar cotas de Redshift no console (limite de nós)")
    return steps